### ISSUE TITLE
`;f`和`oj` 错误

### ISSUE THREAD

**Issue by jqtmviyu** [cubercsl/rime-flypy#11]
`;f` 重复上一个输出, 需要把`|	;f`去掉

```
history:
  input: ;f
  size: 1 #重复前几次上屏
  initial_quality: 1 #首选
```

`oj` 输出 `#`, 实测要在前面行加`# no comment`才能避免被认为注释
