### ISSUE TITLE
10.9.5 单键输入时有三个候选字

### ISSUE THREAD

**Issue by jqtmviyu** [cubercsl/rime-flypy#8]
## 1
10.9.5 单键输入时有三个候选字

原因: flypy_sys.txt 多了一简字

鹤大回复: `因为没有开关，所以二重简码和一简词都显示出来了，根据自己需要，删除其中不需要的就好。`

## 2

似乎要多添加一行才能在build里生成对应的反查码表

```yaml
patch:
  schema_list:
    - schema: flypy # 添加小鹤音形
    - schema: flypydz # 反查码表
```
